### PR TITLE
Update extract.go

### PR DESCRIPTION
**Pull request by Shivkumar13**
**Description of the change:** Updated extract.go, got my eyes on this while reading the code.

**Motivation for the change:**  Updating to have a good reading experience.

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ x] Commit messages sensible and descriptive

### CODE REVIEW

**Review by gallettilance — APPROVED** [review]
lgtm thanks for catching that typo. Please sign your commit:

```
git commit --amend --no-edit --signoff
git push --force-with-lease origin patch-3
```

**Review by ankitathomas — APPROVED** [review]
/lgtm

**Comment by timflannagan** [comment]
@Shivkumar13 It looks like the DCO check still is failing. Lance had posted a comment about how to make the DCO bot happy in https://github.com/operator-framework/operator-registry/pull/876#pullrequestreview-829376868.

**Comment by timflannagan** [comment]
Recycling this PR as there are some prow checks that are showing up in the status for whatever reason.

/lgtm

**Comment by timflannagan** [comment]
Oh, there are prow jobs defined as this PR is targeting the release-4.8 branch. This branch no longer builds downstream, so it's technically a no-op, and I don't think we have any real appetite for backporting these changes to the 4.8 release.

**Comment by joelanford** [comment]
It looks like this typo exists on master, so I'll retarget the PR for the `master` branch.

**Pull request merged**
