### PR TITLE
add further console customization types

### PR DESCRIPTION
**Pull request by dmesser**
**Description of the change:** 
Allow Operators to ship customization extensions for graphical consoles

**Motivation for the change:**
Make it easier to get started with operator provided services by guiding users with quick starts, CLI download links or links to standalone consoles in graphical console for Kubernetes

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by timflannagan** [comment]
These looks like an expansion of support downstream OCP console types - it would be nice to decouple this from upstream one of these days, but I don't think we have much of a choice in the current downstream repository structuring.

/lgtm

**Comment by dmesser** [comment]
@timflannagan I hear you. I think the need for these bespoke lists will go away when we have a more generic approach to process auxiliary resources in a bundle (https://issues.redhat.com/browse/OLM-1781)

**Comment by kevinrizza** [comment]
/hold

OLM needs to support this cr type first:

https://github.com/operator-framework/operator-lifecycle-manager/blob/master/pkg/controller/operators/catalog/operator.go#L2443

**Comment by timflannagan** [comment]
Manually merging as it looks like tide is blocking waiting for an out-of-date required context to report a success.

**Pull request merged**
