### PR TITLE
 (fix) database is locked during remove

### PR DESCRIPTION
**Pull request by gallettilance**
Signed-off-by: Lance Galletti <galletti@bu.edu>

**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Review by anik120 — APPROVED** [review]
/lgtm

Worked for me locally. 

Ideally we'd like to have some test cases for `rmStrandedBundles`. I'm guessing that could have helped catch concurrent db access. This change is simple enough though and makes sense to me by itself.

**Comment by anik120** [comment]
@gallettilance also, we're not using bugzilla numbers in our upstream projects anymore.

**Review by ankitathomas — APPROVED** [review]
/lgtm

**Review by dinhxuanvu — APPROVED** [review]
/approve

**Pull request merged**
