### PR TITLE
Bug 1904547: Include the bundle image itself as a related image.

### PR DESCRIPTION
**Pull request by benluddy**
Backport of #527 to 4.6.

### CODE REVIEW

**Comment by kevinrizza** [comment]
@benluddy doesn't this need a bz?

**Comment by benluddy** [comment]
> @benluddy doesn't this need a bz?

Yes, was just waiting on confirmation that there were no changes needed to the original patch before cloning it. It's been verified now so I'll go ahead and do that now.

**Comment by benluddy** [comment]
@kevinrizza PTAL, it's just been rebased onto the latest release-4.6.

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Pull request merged**
