### PR TITLE
(feat) Load operator registry bundle from ConfigMap

### PR DESCRIPTION
**Pull request by tkashem**
- Iterate through the Data section of a ConfigMap, process each
  resource and construct a registry.Bundle object for use.
- The ConfigMap may have a resource that contains a `PackageManifest`
  resource. Process this resource if present and deserialize.

### CODE REVIEW

**Comment by jpeeler** [comment]
/hold cancel
Removing the hold as the added commit made by me verifies that this code will work correctly and no further changes are known at present. (Though it might be nice if #94 is merged first just in case.)

**Comment by ecordell** [comment]
this will need to change slightly when this merges: https://github.com/openshift/enhancements/pull/70

**Comment by jpeeler** [comment]
I forgot this depends on constants in https://github.com/operator-framework/operator-registry/pull/94.

**Comment by jpeeler** [comment]
Removed the dependency on #94. Also, decided to keep the latest commit separate since these commits evolved over time with different authors instead of squashing it all together.

**Pull request merged**
