### PR TITLE
Update k8s dependencies to v0.28.5

### PR DESCRIPTION
**Pull request by Neo2308**
Update k8s dependencies to v0.28.5
Update operator-framework/api dependency which has k8s 1.28 changes

Relates to: https://github.com/operator-framework/operator-sdk/issues/6554

**Reviewer Checklist**
- [x] Implementation matches the proposed design, or proposal is updated to match implementation
- [x] Sufficient unit test coverage 
- [x] Sufficient end-to-end test coverage
- [x] Docs updated or added to `/docs` 
- [x] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by grokspawn** [comment]
Needs merge conflicts resolved.

**Comment by joelanford** [comment]
I rebased and removed the operator-framework/api dependency change. Let's do that one separately.

**Pull request merged**
