### PR TITLE
(vendor) bump go-sqlite3 to 1.14.10

### PR DESCRIPTION
**Pull request by nsapse**
This commit bumps operator-framework/operator-registry requirement
go-sqlite3 from v1.10.0 to v1.14.10

**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
The title is misleading. You bump `go-sqlite3` dependency, not `operator-registry`.

**Comment by nsapse** [comment]
Good point - changed the PR title. My apologies.

**Comment by dinhxuanvu** [comment]
The sanity check doesn't pass. Did you run `make vendor`?

**Comment by nsapse** [comment]
Ran make vendor and re-submitted.

**Comment by dinhxuanvu** [comment]
The merge commit shouldn't be there. You will need to do a proper rebase and squash those commits into a single one.

**Comment by nsapse** [comment]
Rebased (hopefully properly)

**Comment by timflannagan** [comment]
@nsapse Can we also update the commit message to reflect that we're bumping the go-sqlite3 dependency in this PR?

**Comment by nsapse** [comment]
Updated

**Review by dinhxuanvu — APPROVED** [review]
Looking good.

**Pull request merged**
