### PR TITLE
[release-4.6] Bug 1898746: fix(indexing): order bulk add by version field

### PR DESCRIPTION
**Pull request by njhale**
Manual cherry-pick of #503 and two updates to fix its defects:
- Respect strict mode: https://github.com/operator-framework/operator-registry/pull/523
- Include default channel definition in input order: https://github.com/operator-framework/operator-registry/pull/528

When adding more than one bundle to an index in replaces mode, sort the input by order of ascending version field (semver). This ensures a deterministic update graph in the absence of a replaces field.

The replaces field takes priority.

### CODE REVIEW

**Review by hasbro17 — APPROVED** [review]
/lgtm

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by njhale** [comment]
/hold

some weirdness going on here

**Comment by njhale** [comment]
/hold cancel

Was unintentionally bumping k8s deps to 1.19, which pulled in a transitive dep that underwent a file name case-change, which confused my case-insensitive -- but case-preservative --  macos filesystem; Git did not pick up the changes to the file name in the vendor directory, and CI -- both travis and openshift -- determined there was a missing dependency.

I removed the 1.19 bump and it looks like the builds are working now.

Thanks @benluddy for your help!

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by njhale** [comment]
/hold

There are some questions about whether this is causing a regression. More details to follow.

**Comment by njhale** [comment]
/hold cancel

Regressions fixed and included in this patch.

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Pull request merged**
