### PR TITLE
Use local docker registry for e2e tests on PRs

### PR DESCRIPTION
**Pull request by njhale**
**Description of the change:**

- Start and use a local docker registry in travis e2e tests for unprivileged branches/PRs.
- Introduce the `$DOCKER_REGISTRY_HOST` environment variable to configure the registry host used in OPM e2e tests.

**Motivation for the change:**

E2E tests requiring Quay creds were being skipped for PR branches, so we wouldn't see the results until it had already merged to master.

### CODE REVIEW

**Comment by ecordell** [comment]
/lgtm
/approve

podman tests are failing, but they're failing in master as well.

**Comment by njhale** [comment]
going to close this out for now

**Comment by exdx** [comment]
@njhale just wondering, why was this ultimately closed? Is it podman related? I'm looking to implement something very similar for our upstream tests on GH Actions

**Pull request closed without merging**
