### PR TITLE
Move config serve and validate to opm alpha

### PR DESCRIPTION
**Pull request by dinhxuanvu**
The serve and validate commands for declarative config are not yet
ready for production use and there are changes that will potentially
alter the functionality significantly. As a result, both commands
are moved to be under `alpha`.

Signed-off-by: Vu Dinh <vudinh@outlook.com>

**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Review by joelanford — APPROVED** [review]
/lgtm

**Comment by joelanford** [comment]
/hold

@timflannagan I didn't expect tide to automatically pick up the go-apidiff check as a required check. Can we permanently exempt it and make it optional?

**Comment by joelanford** [comment]
@dinhxuanvu If you want to go ahead and get this merged, its safe to manually merge. The go-apidiff test is meant to be optional/informational.

**Comment by timflannagan** [comment]
@joelanford Hmm, I'm surprised by that as well. It looks like it's not marked as a required check in the context of thoss status check, but tide is still there influenced by it.

/Hold cancel

**Comment by timflannagan** [comment]
I might have some time later today to tinker with the tide configuration. I'd like to somehow get the ability to override non-prow based tests. Feel free to manually merge if everyone is on board with the changes.

/Hold

**Comment by dinhxuanvu** [comment]
I'll keep the PR hold until the end of the week and will merge it on Friday.

**Comment by joelanford** [comment]
/hold

Just wanted to see if tide would ignore go-apidiff this time around, but no. Tide still considers it a required check.

**Pull request merged**
