### PR TITLE
Add test to verify empty bundles in addition does not break

### PR DESCRIPTION
**Pull request by shawn-hurley**
**Description of the change:**
Test to verify the behavior of adding an empty list of bundles

**Motivation for the change:**
Prevent backwards incompatible changes.

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by njhale** [comment]
/lgtm

tide should just be waiting for a merge window now

**Comment by shawn-hurley** [comment]
@ecordell can you override with valid bug? I believe the change is just a test change and is needed to make sure that we don't break pipeline functionality

**Comment by ecordell** [comment]
this a safe, test-only change, marking with `valid-bug`

**Pull request merged**
