### PR TITLE
Bug 1885425: fix(indexing): order bulk add by version field

### PR DESCRIPTION
**Pull request by njhale**
When adding more than one bundle to an index in replaces mode, sort the input by order of ascending version field (semver). This ensures a deterministic update graph in the absence of a replaces field.

The replaces field takes priority.

### CODE REVIEW

**Comment by yashvardhannanavati** [comment]
Can I please ask what's the time-frame of this PR getting merged?

**Comment by njhale** [comment]
/hold cancel

> Can I please ask what's the time-frame of this PR getting merged?

@yashvardhannanavati I'm requesting reviews now. If all goes well it should be in today.

**Comment by njhale** [comment]
/hold

e2e-aws consistently failing. investigating now.

**Comment by njhale** [comment]
/hold cancel

The failures don't seem to be isolated to this PR or operator-registry. DPTP is looking into the problem (see https://coreos.slack.com/archives/CEKNRGF25/p1605530888050100)

**Pull request merged**
