### PR TITLE
add skipRange support to render-graph

### PR DESCRIPTION
**Pull request by grokspawn**
Signed-off-by: Jordan Keister <jordan@nimblewidget.com>

**Description of the change:**
mermaid output of channels will express skipRange relationships between nodes

**Motivation for the change:**
tired of the header/footer always expressing the feature's shortcomings ;) 

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by cdjohnson** [comment]
Thanks for doing this.  I tried it out against one our packages:  `ibm-mq`. 

 Question:  This clearly shows the graph between bundles.  Is there any thought of showing the upgrade graphs between channels, so one can see the intra-channel upgrade paths a bit more obviously?  

Maybe it would be a different render command, or it would get too busy?

E.g. Make it obvious that you can move from any channel to the v2.0 channel.  We have other examples, where one needs to traverse from v1.0 to v1.1 to v2.0 and directly from v1.0 to v2.0.  

Here's what the `ibm-mq` one looks like:
mq

**Comment by grokspawn** [comment]
I'm abandoning this PR in favor of #1023.  There started to be complex interactions between the different filtering options, and an increasing burden of sequencing the PRs was just more than I wanted to countenance.  
I'll read through the feedback so far and see what I can incorporate...  I'm not ignoring it.  It's just that I had to consolidate to reduce complexity.

**Comment by grokspawn** [comment]
> Thanks for doing this. I tried it out against one our packages: `ibm-mq`.
> 
> Question: This clearly shows the graph between bundles. Is there any thought of showing the upgrade graphs between channels, so one can see the intra-channel upgrade paths a bit more obviously?
> 
> Maybe it would be a different render command, or it would get too busy?
> 
> E.g. Make it obvious that you can move from any channel to the v2.0 channel. We have other examples, where one needs to traverse from v1.0 to v1.1 to v2.0 and directly from v1.0 to v2.0.
> 
> Here's what the `ibm-mq` one looks like: mq

That is really cool!  

I hadn't really ever thought about inter-channel linkages before, honestly.  It would definitely make the graph more noisy.  I'll give it a look.

**Comment by bentito** [comment]
The CNV folks have expressed a desire for inter-index graphs as well. That is, it would show the way to proceed when you move to another index.

**Pull request closed without merging**
