### PR TITLE
.github/workflows: Add action that emulates tide commands

### PR DESCRIPTION
**Pull request by timflannagan**
**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by timflannagan** [comment]
Ah, didn't see this part:

```
Caveat: because of Action limitations, only failed workflows can be rerun.
```

**Comment by timflannagan** [comment]
Hmm, this doesn't seem like it plays well with tide also listening for retest/test commands, or we need to merge this first before we see any changes propagate.

/hold

**Comment by estroz** [comment]
@timflannagan calling `/retest` works, but `/test <workflow>` conflicts with tide. It may be worth renaming the command to `/run-test <workflow>` to avoid conflicts.

**Comment by timflannagan** [comment]
@estroz Yeah I had forked your project with that same thought in mind 😆 as a quick, short term workaround. I think I'd prefer to keep using tide in the OLM-related repositories, but I'm a fan of the action so I thought I'd give it a spin.

**Comment by estroz** [comment]
I'd like to have the action work alongside tide as well as possible, so the command name change is welcome.

**Comment by timflannagan** [comment]
I'll save you guys the future notifications while I play around with this

/uncc estroz
/uncc anik120

**Review by dinhxuanvu — APPROVED** [review]
/approve

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Pull request merged**
