### PR TITLE
OWNERS: Remove timflannagan as a reviewer

### PR DESCRIPTION
**Pull request by timflannagan**
**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by timflannagan** [comment]
@grokspawn would you be able to help push this through?

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by dinhxuanvu** [comment]
Look like opensuse.org is down. Will rerun the test later.

**Comment by timflannagan** [comment]
@dinhxuanvu thanks for the assist 👍

**Pull request merged**
