### PR TITLE
Bug 1907632: Bump k8s deps to 1.20

### PR DESCRIPTION
**Pull request by awgreene**

### CODE REVIEW

**Comment by awgreene** [comment]
/retest

```
Dec 15 04:16:23.091: INFO: At 2020-12-15 04:14:39 +0000 UTC - event for sample-apiserver-deployment-d66f77fb4-2nmcg: {kubelet ip-10-0-176-34.us-west-1.compute.internal} FailedMount: MountVolume.SetUp failed for volume "default-token-gksbz" : failed to sync secret cache: timed out waiting for the condition
```

**Review by hasbro17 — APPROVED** [review]
/lgtm

**Review by dinhxuanvu — APPROVED** [review]
/approve

**Comment by dinhxuanvu** [comment]
The PR looks good but this failure on e2e-kind test doesn't seem to go away.

**Comment by hasbro17** [comment]
Mentioned offline but the CI failures were always there, they are just more visible now after https://github.com/operator-framework/operator-registry/pull/536
I'll be following up to get the tests to use a local registry but there might still be issues beyond that. So the `test / e2e-kind` failure is unrelated to this PR.

**Pull request merged**
