### PR TITLE
Bug 1873916: Display the deprecatetruncate command

### PR DESCRIPTION
**Pull request by jianzhangbjz**
**Description of the change:**
After this PR, it will display the `deprecatetruncate` sub-command in the output of the `opm index --help`
```console
mac:operator-registry jianzhang$ ./bin/opm index --help
generate operator index container images from preexisting operator bundles

Usage:
  opm index [command]

Available Commands:
  add               Add operator bundles to an index.
  deprecatetruncate Deprecate and truncate operator bundles from an index.
  export            Export an operator from an index into the appregistry format
  prune             prune an index of all but specified packages
  prune-stranded    prune an index of stranded bundles
  rm                delete an entire operator from an inde
```

**Motivation for the change:**
Let the end user aware of this command easily.

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by kevinrizza** [comment]
@jianzhangbjz This is hidden on purpose, because we don't want to expose this command to be used by users. Ideally this command should be removed and split out into several other commands.

**Comment by jianzhangbjz** [comment]
@kevinrizza Thanks for your information! Actually, after reviewing this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1873483 I thought you want to public this sub-command, and just missed this `Hidden` setting, so I submitted it.

**Comment by jianzhangbjz** [comment]
/retitle Bug 1873916: Display the deprecatetruncate command

**Comment by njhale** [comment]
Closing this out b/c this command is hidden by design.

**Pull request closed without merging**
