### PR TITLE
Bug 1881527: Add e2e tests for export directory structure

### PR DESCRIPTION
**Pull request by ankitathomas**
The multi-package export in https://github.com/operator-framework/operator-registry/pull/429 changed the bundle export path, breaking pipelines depending on the old path format. Switching to the old behavior for single package exports.

### CODE REVIEW

**Review by kevinrizza — COMMENTED** [review]
Didn't we also want to revert the change to the parameter?

**Comment by ankitathomas** [comment]
> Didn't we also want to revert the change to the parameter?

There are other opm index commands that use -p for the package flag, I thought we should have uniformity across our commands for flags

**Comment by kevinrizza** [comment]
Yeah, you're right. Let's try to unify everything later, and get this fix in for now.

/approve

**Comment by shawn-hurley** [comment]
/hold

When discussed with the pipeline, they asked us to keep the new behavior. 

Is anyone else needing this to stay the same? If we need to keep it the same, we have to coordinate the release of this update with the changes in IIB to revert back.

**Comment by ankitathomas** [comment]
> Didn't we also want to revert the change to the parameter?

I've added back `-o` as a deprecated flag

**Review by gallettilance — APPROVED** [review]
/lgtm

**Comment by njhale** [comment]
since we need to keep the new behavior, I'm going to close this out in favor of a flag alias PR: https://github.com/operator-framework/operator-registry/pull/485

**Pull request closed without merging**
