### PR TITLE
Bug 1883560: Clean up /tmp/directory in the operator-registry image

### PR DESCRIPTION
**Pull request by akram**
Clean up /tmp/directory in the operator-registry image

The image is 320MB with 265MB just in /tmp

### CODE REVIEW

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by ecordell** [comment]
/hold

this will break mac and windows builds

**Comment by njhale** [comment]
/lgtm remove

multiplatform builds require a glob so we can use the same Dockerfile for each platform -- sorry for premature lgtm

**Comment by njhale** [comment]
Closing this out as another patch fixing it has merged.

**Pull request closed without merging**
