### PR TITLE
removing docker registry replace

### PR DESCRIPTION
**Pull request by grokspawn**
**Description of the change:**

removing 
```
replace github.com/docker/distribution => github.com/docker/distribution v0.0.0-20191216044856-a8371794149d
```
from go.mod

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Review by everettraven — APPROVED** [review]

**Review by tmshort — APPROVED** [review]
re: API diff:
`github.com/docker/distribution` redirects to `github.com/distribution/distribution`, so it shouldn't be too big of a deal.
re: codecov:
very minor, not concerned

**Pull request merged**
