### PR TITLE
WIP: remove opm alpha bundle [build|generate|validate] commands

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description of the change:**
- Remove alpha command [build|generate|validate]

**Motivation for the change:**
These actions ought to get done and maintained via SDK. 
Closes: https://github.com/operator-framework/operator-registry/issues/561

### CODE REVIEW

**Comment by kuiwang02** [comment]
Hi,

 During daily work, we always generate bundle per manifest of the community operator with opm alpha bundle command.
For example,
  1, get all of https://github.com/operator-framework/community-operators/tree/master/community-operators/cockroachdb local directory, like manifests/cockroachdb
```console
[root@preserve-olm-env manifests]# tree cockroachdb
cockroachdb
|-- 2.0.9
|   |-- cockroachdbs.charts.helm.k8s.io.crd.yaml
|   `-- cockroachdb.v2.0.9.clusterserviceversion.yaml
|-- 2.1.1
|   |-- cockroachdbs.charts.helm.k8s.io.crd.yaml
|   `-- cockroachdb.v2.1.1.clusterserviceversion.yaml
|-- 2.1.11
|   |-- cockroachdbs.charts.helm.k8s.io.crd.yaml
|   `-- cockroachdb.v2.1.11.clusterserviceversion.yaml
|-- 3.0.7
|   |-- charts_v1alpha1_cockroachdb_crd.yaml
|   `-- cockroachdb.v3.0.7.clusterserviceversion.yaml
`-- cockroachdb.package.yaml

4 directories, 9 files

 ```
2, modify yaml per test purpose, and then put them into another directory, like cockroachdb-29810
```console
[root@preserve-olm-env manifests]# tree cockroachdb-29810
cockroachdb-29810
|-- 2.0.9
|   |-- cockroachdbs.charts.helm.k8s.io.crd.yaml
|   `-- cockroachdb.v2.0.9.clusterserviceversion.yaml
|-- 2.1.1
|   |-- cockroachdbs.charts.helm.k8s.io.crd.yaml
|   `-- cockroachdb.v2.1.1.clusterserviceversion.yaml
|-- 2.1.11
|   |-- cockroachdbs.charts.helm.k8s.io.crd.yaml
|   `-- cockroachdb.v2.1.11.clusterserviceversion.yaml
|-- 3.0.7
|   |-- charts_v1alpha1_cockroachdb_crd.yaml
|   `-- cockroachdb.v3.0.7.clusterserviceversion.yaml
|-- ci.yaml
`-- cockroachdb.package.yaml

4 directories, 10 files

```
3, build bundle with opm alpha bundle command
```console
[root@preserve-olm-env operator-registry]# ./bin/opm alpha bundle build -d manifests/cockroachdb-29810/2.0.9 -t quay.io/kuiwang/cockroachdb-operator:2.0.9-29810 -c alpha -p cockroachdb -e alpha
INFO[0000] Building annotations.yaml                    
INFO[0000] Writing annotations.yaml in /root/kuiwang/operator-registry/manifests/cockroachdb-29810/metadata 
INFO[0000] Building Dockerfile                          
INFO[0000] Writing bundle.Dockerfile in /root/kuiwang/operator-registry 
INFO[0000] Building bundle image                        
Sending build context to Docker daemon  122.4MB
Step 1/9 : FROM scratch
 ---> 
Step 2/9 : LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
 ---> Using cache
 ---> b04718d9d9d6
Step 3/9 : LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
 ---> Using cache
 ---> cba2669aa2db
Step 4/9 : LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
 ---> Using cache
 ---> a903be0ee511
Step 5/9 : LABEL operators.operatorframework.io.bundle.package.v1=cockroachdb
 ---> Using cache
 ---> b84ccfcebaee
Step 6/9 : LABEL operators.operatorframework.io.bundle.channels.v1=alpha
 ---> Using cache
 ---> cdc1c6551507
Step 7/9 : LABEL operators.operatorframework.io.bundle.channel.default.v1=alpha
 ---> Running in 4a92799247f7
Removing intermediate container 4a92799247f7
 ---> 0fb2ccfdb8d0
Step 8/9 : COPY manifests/cockroachdb-29810/2.0.9 /manifests/
 ---> cc0b9cd86820
Step 9/9 : COPY manifests/cockroachdb-29810/metadata /metadata/
 ---> 8fd7bfa4aced
Successfully built 8fd7bfa4aced
Successfully tagged quay.io/kuiwang/cockroachdb-operator:2.0.9-29810
```

if there is no "opm alpha bundle" command any more, how do we build bundle per manifest, not executing "make bundle" in certain project (like https://sdk.operatorframework.io/docs/olm-integration/quickstart-bundle/) because we have no project? Thanks

cc @jianzhangbjz

**Comment by jianzhangbjz** [comment]
@kuiwang02  I guess operator-sdk will support those actions before this PR merged, no worries. 
@camilamacedo86 Hi, thanks for your PR. But, one concern, for now, the `opm alpha bundle extract` is used to extract manifests to a `ConfigMap` when subscribing to an operator. Like this:
```console
...
  name: cc8c72b382bd1ac5ca006964332b9f198745bc52b7851422b254d4dcc55d8c0
  namespace: openshift-marketplace
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: false
    controller: false
    kind: ConfigMap
    name: cc8c72b382bd1ac5ca006964332b9f198745bc52b7851422b254d4dcc55d8c0
    uid: f57f6885-6c50-4935-93dd-10bab5187850
  resourceVersion: "50676"
  selfLink: /apis/batch/v1/namespaces/openshift-marketplace/jobs/cc8c72b382bd1ac5ca006964332b9f198745bc52b7851422b254d4dcc55d8c0
  uid: 9701bfcb-af93-42e1-bb2f-1fb08f98b01b
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 9701bfcb-af93-42e1-bb2f-1fb08f98b01b
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 9701bfcb-af93-42e1-bb2f-1fb08f98b01b
        job-name: cc8c72b382bd1ac5ca006964332b9f198745bc52b7851422b254d4dcc55d8c0
      name: cc8c72b382bd1ac5ca006964332b9f198745bc52b7851422b254d4dcc55d8c0
    spec:
      containers:
      - command:
        - opm
        - alpha
        - bundle
        - extract
        - -m
        - /bundle/
        - -n
        - openshift-marketplace
        - -c
        - cc8c72b382bd1ac5ca006964332b9f198745bc52b7851422b254d4dcc55d8c0
              env:
        - name: CONTAINER_IMAGE
          value: quay.io/openshift-community-operators/etcd:v0.9.4
        image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:2dc1f2071e9c5ae8fb9b6176440052f54a1ce1e1b822bc0c16e11a2c7dfd0e10
        imagePullPolicy: IfNotPresent
        name: extract
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bundle
          name: bundle
      dnsPolicy: ClusterFirst
      initContainers:
...
```
This image `        image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:2dc1f2071e9c5ae8fb9b6176440052f54a1ce1e1b822bc0c16e11a2c7dfd0e10` is the `operator-registry` image that built from this repo. If you removed these `opm alpha bundle` commands, how to handle this? Replace it with `operator-sdk`? Thanks!

**Comment by camilamacedo86** [comment]
HI @kuiwang02, 

SDK allows you to work with bundles. See [here](https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/Makefile#L126-L131) that the `make bundle` call the command `operator-sdk generate`. This command is not alpha and allows you to generate bundles for Non-SDK projects as well. We need to update the docs too.  

Hi @jianzhangbjz, 

I did not have the extract option so far. After this PR gets merged the `opm alpha bundle extract` will still available here. However, could you help me understand better when/why the `opm alpha bundle extract` is required?

c/c @dmesser

**Comment by kuiwang02** [comment]
Hi @camilamacedo86 in order to use [here](https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/Makefile#L126-L131), we have project firstly. For scenario I describe, there is no project and as well no Makefile etc. It is different.
  So, I think the [here](https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/Makefile#L126-L131) can not resolve the scenario I describe. 

Thanks.

**Comment by jianzhangbjz** [comment]
Hi @camilamacedo86 ,
> SDK does not have the extract option. So, because of this PR does not remove the opm alpha bundle extract and it will still available in opm so far.

Ah, sorry, my mistake. But, it's better if we can replace all of the `opm alpha` commands with SDK at a time. 

> However, could you help me understand better when/why the opm alpha bundle extract is required? What is the scenario/use case that solves?

It happens when subscribing to the operator on OCP. That's the very basic use case.

**Comment by jianzhangbjz** [comment]
@camilamacedo86  One question, just as Kui asked above, if we remove the `opm alpha bundle build` command, how to generate the `bundle image` from the local manifests files with SDK?

**Comment by camilamacedo86** [comment]
Hi @jianzhangbjz, @kuiwang02, 

> @camilamacedo86 One question, just as Kui asked above, if we remove the opm alpha bundle build command, how to generate the bundle image from the local manifests files with SDK?

You will use `operator-sdk generate bundle` and inform the dir where the files, the output-dir and etc. You can use the `--help` flag to check all available options. Also, we need to document that better and I raise some issues over that. See: https://github.com/operator-framework/operator-sdk/issues/4442, https://github.com/operator-framework/operator-sdk/issues/4528

After some chats with @kevinrizza over this topic, we might decide here only clarifies that it is an **alpha** command added on the tool for development and test purposes instead of remove.

**Comment by jmrodri** [comment]
Why are we removing these? This shouldn't be removed *until* operator-sdk gets them. And there were also some questions about these in operator-sdk as well. I really think we need to be careful about removing things from opm prematurely.

**Comment by camilamacedo86** [comment]
Hi @jmrodri,  

In the `On-Top Pillar Architecture` on January 20th, 2021 this topic was discussed and we reach the consensus that these commands should be removed. However, please see the comment: https://github.com/operator-framework/operator-registry/pull/563#issuecomment-779859997. 

> Why are we removing these? This shouldn't be removed until operator-sdk gets them. 
SDK already has these commands/features addressed it only required to be better documented/described. 

> I really think we need to be careful about removing things from opm prematurely.
After spoke with @kevinrizza over this topic, we might decide here only clarifies that it is an alpha command added on the tool for development and test purposes instead of remove.

I hope that it clarifies your questions.

**Comment by estroz** [comment]
For clarity the only command equivalents that exist in operator-sdk are:
1. `opm alpha bundle generate`  -> `operator-sdk generate bundle`
1. `opm alpha bundle validate`  -> `operator-sdk bundle validate`

No other commands are on the roadmap. You can however combine `operator-sdk generate bundle` and `docker build` to get a lot if not all functionality of `opm alpha bundle build`.

IIRC (2) above behave differently, as the opm command will always error if some validator has warnings, while the operator-sdk command will not.

**Comment by dinhxuanvu** [comment]
There is no reason to remove those commands as they are intended for local/development/testing usage only. Hence, they are under `alpha` and not visible under help command. The SDK is still the official tool to do all tasks for bundle-related commands.
I recommend to close this PR.

**Comment by camilamacedo86** [comment]
Hi @dinhxuanvu, 

As described above we decided to not remove ( it is wip because of this )

I kept this open to remember to see if we could improve the log/description to clarifies that is for dev purposes. 
however, you re right. I will close and then, raise a new on to improve the cmd output if we see that is required.

**Pull request closed without merging**
