### PR TITLE
[release-4.5] Bug 1845588: fix(images): use docker/podman create and cp for exec unpacking

### PR DESCRIPTION
**Pull request by njhale**
Manual cherry-pick of interdependent fixes #351 and #390

### CODE REVIEW

**Comment by shawn-hurley** [comment]
/hold

I think we need to determine if this is the fix we want to make

**Comment by njhale** [comment]
> /hold
> 
> I think we need to determine if this is the fix we want to make

Could you elaborate a little on why we wouldn't want to backport this fix? alternatives?

(I figure there might be some discussion I missed or maybe some connection to our version skew discussions that I'm not making)

**Comment by njhale** [comment]
/hold cancel

@shawn-hurley, following up on our Slack discussion, I've removed the unintentional inclusion of the `none` container tool option from this patch. Nice catch!

PTAL

**Comment by eparis** [comment]
not sure what happened to tide over teh weekend, but this didn't merge, so pulling the label

**Pull request merged**
