### PR TITLE
fix(dns): fix slow dns resolution of localhost for grpc health probe

### PR DESCRIPTION
**Pull request by ecordell**
**Description of the change:**
Adds an nsswitch.conf to prefer local files over dns for resolution. 

**Motivation for the change:**
see: https://github.com/golang/go/issues/35305

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by njhale** [comment]
Cool! Here's what I found:

1. I think we should add the file for all [generated Dockerfiles](https://github.com/operator-framework/operator-registry/blob/d2e885544104bf40d9f6c4e9e462a8f6e43d4616/pkg/containertools/dockerfilegenerator.go#L35), since we don't know if the given base image contains it. 
2. Looks like image builds are failing on [chmod to `/dev`](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/operator-framework_operator-registry/227/pull-ci-operator-framework-operator-registry-master-images/605/build-log.txt). I don't think the failure is related to any changes here. Since the blame is months old, my primary suspect is that the base image was swapped out under us in CI again.

**Comment by ecordell** [comment]
> I think we should add the file for all generated Dockerfiles, since we don't know if the given base image contains it.

This is tricky, since the source image can vary on user input and there's no guarantee we'll have `echo`

**Comment by njhale** [comment]
@ecordell, then do you think opm should just attempt to generate the file at runtime?

**Comment by ecordell** [comment]
@njhale Updated with your suggestion.

In the downstream image, nsswitch is already populated correctly. I tested with the upstream image as well:

```sh
/go # cat /etc/nsswitch.conf
cat: can't open '/etc/nsswitch.conf': No such file or directory
/go # /registry-server &
/go # cat /etc/nsswitch.conf
hosts: files dns/go
```

**Pull request merged**
