### PR TITLE
fix the description of validation "RegistryV1" format

### PR DESCRIPTION
**Pull request by dongwenjuan**
Signed-off-by: dongwenjuan <dong.wenjuan@zte.com.cn>

**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by njhale** [comment]
@dongwenjuan we appreciate you taking the time to make this change, but for future reference, we typically hold off on including such small doc/style changes until we have a more substantive patch that we can include them in.

/lgtm
/approve

**Comment by dongwenjuan** [comment]
> @dongwenjuan we appreciate you taking the time to make this change, but for future reference, we typically hold off on including such small doc/style changes until we have a more substantive patch that we can include them in.
> 
> /lgtm
> /approve

OK, thanks~

**Comment by njhale** [comment]
Docs only, bypassing infra issues for this one.

/override ci/prow/e2e-aws

**Pull request merged**
