### PR TITLE
removing channel property as a remnant of oc mirror diff migration

### PR DESCRIPTION
**Pull request by grokspawn**
**Description of the change:**

**Motivation for the change:**
removing remnants left behind when oc mirror migrated the alpha diff capabilities to it

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by joelanford** [comment]
/lgtm

/hold
Looks like this is still used in oc-mirror: https://github.com/openshift/oc-mirror/blob/1183c30d32ecd2a68fd607a684a51bdb87e62699/pkg/operator/diff/internal/diff.go#L208

Feel free to unhold whenever you're comfortable with whatever comms you deem appropriate for the oc-mirror folks. (e.g. new issue, PR, slack message, whatever makes sense)

**Comment by grokspawn** [comment]
Started an internal slack convo to discuss
https://redhat-internal.slack.com/archives/C02JW6VCYS1/p1677000215625349

**Comment by joelanford** [comment]
/lgtm cancel

Need to remove this line as well: https://github.com/operator-framework/operator-registry/blob/1446d7be762d9eb3c88dddb2828a61debdcd6cd6/alpha/property/property.go#L142

**Comment by perdasilva** [comment]
closing PR as stale. Please re-open if it's still important.

**Pull request closed without merging**
