### PR TITLE
Bug 1794177: Updating summary for 'Operator Registry ' containers

### PR DESCRIPTION
**Pull request by Bowenislandsong**
**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
@operator-framework/patch-managers PTAL. Thanks

**Comment by bparees** [comment]
> @operator-framework/patch-managers PTAL. Thanks

no need to do this unless you have reason to believe it's been overlooked or you have a specific concern/question about it.  patch managers review all the backport PRs every wed/thur/fri.

**Comment by dinhxuanvu** [comment]
@bparees Hey Ben. No this is just a regular PR, no priority or anything. I thought I needed to tag patch managers manually for review. Thanks for the information.

**Comment by ashcrow** [comment]
This does not look like a critical 4.1 fix.

**Comment by mfojtik** [comment]
@bparees only critical fixes in 4.1 now and I agree with @ashcrow that this is not critical. I vote for close?

**Comment by bparees** [comment]
@mfojtik +1

/close

**Pull request closed without merging**
