### PR TITLE
Bug 1951387: (bug) add after deprecation

### PR DESCRIPTION
**Pull request by gallettilance**
**Description of the change:**

Could not add after deprecation because the graph is rebuilt on every add based on the information stored in the operatorbundle table. The table contains replaces refs to bundles that have been truncated causing add to fail.

Solution: empty the replaces field in the operatorbundle table for deprecated bundles

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
I don't think this change is enough as we made some changes to only use `channel_entry` table to the source of truth to form the upgrade graph. This PR only updates the `operatorbundle` table and that may not be enough. Bring @benluddy in for further review.

**Comment by gallettilance** [comment]
the channel_entry table is taken care of through the deletion of the replacements bundles which cascades

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by dinhxuanvu** [comment]
> I don't think this change is enough as we made some changes to only use `channel_entry` table to the source of truth to form the upgrade graph. This PR only updates the `operatorbundle` table and that may not be enough. Bring @benluddy in for further review.

We had a discussion further on Slack and it was determined that the `replaces` info between `channel_entry` and `operatorbundle` are kept in sync via FK constraint and additional query. So this is no longer a concern.

**Pull request merged**
