### PR TITLE
Bump to Go 1.16

### PR DESCRIPTION
**Pull request by joelanford**
**Description of the change:**
Bump all operator-registry builds to Go 1.16

**Motivation for the change:**
Update to latest version of Go.

### CODE REVIEW

**Review by dinhxuanvu — APPROVED** [review]
Approved.

**Comment by timflannagan** [comment]
Can we update the root Dockerifle as well?

/hold

**Comment by timflannagan** [comment]
Nevermind, that's only applicable for the OLM repository.

/hold cancel

**Comment by timflannagan** [comment]
Re-testing, but this continues to pop up in the e2e failures.

```
Summarizing 1 Failure:

[Fail] opm alpha bundle for an invalid bundle [It] fails to unpack 
/home/runner/work/operator-registry/operator-registry/test/e2e/opm_bundle_test.go:90
```

**Pull request merged**
