### PR TITLE
Bug 1883560: fix(dockerfile): clean out tmp directory after binaries are placed

### PR DESCRIPTION
**Pull request by ecordell**
**Description of the change:**
Remove bins from /tmp after they've been moved into the correct location

**Motivation for the change:**
The image was much larger than it needed to be.

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by ecordell** [comment]
closing in favor of #460

**Review by hasbro17 — APPROVED** [review]
/lgtm

**Pull request merged**
