### PR TITLE
updating operator-framework/api dependency which has k8s 1.28 changes

### PR DESCRIPTION
**Pull request by acornett21**
**Description of the change:**
Updating dependencies to support k8s 1.28.

**Motivation for the change:**
To stay current with dependencies.

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

- Relates: operator-framework/operator-sdk#6554

### CODE REVIEW

**Comment by joelanford** [comment]
/hold

I'd like to get any remaining dep bumps into the operator-framework/api repo, then cut a release. That way we, we can pin to a tag here rather than a commit.

**Comment by joelanford** [comment]
@acornett21 I tagged https://github.com/operator-framework/api/releases/tag/v0.21.0. Can you update this PR to use that?

**Comment by acornett21** [comment]
@joelanford Thanks for cutting the release. I updated to the release version.

**Pull request merged**
